version: '3.8'

services:
  # ==========================================
  #  VERİTABANI KATMANI
  # ==========================================
  postgres-db:
    image: postgres:15
    container_name: vip-postgres
    environment:
      POSTGRES_USER: vip_user
      POSTGRES_PASSWORD: vip_password
      POSTGRES_DB: vip_db
    volumes:
      # sql-scripts klasöründeki SQL dosyalarını veritabanı ilk kurulduğunda otomatik çalıştırması için içeri aktarıyoruz
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - vip-network
    restart: unless-stopped
    # DİKKAT: ports komutu YOK! Dışarıdan erişilemez.

  # ==========================================
  # API GATEWAY
  # ==========================================
  api-gateway:
    image: nginx:latest
    container_name: vip-api-gateway
    ports:
      - "8080:80" # Kullanıcılar localhost:8080 üzerinden girecek
    volumes:
      # Az önce oluşturduğumuz nginx.conf dosyasını konteynerin içine bağlıyoruz
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - reservation-service
    networks:
      - vip-network
    restart: unless-stopped

  # ==========================================
  # MİKROSERVİSLER
  # ==========================================
  
  auth-service:
    build: 
      context: ./backend/auth-service # Java kodlarının bulunduğu dizin
    container_name: vip-auth
    depends_on:
      - postgres-db
    networks:
      - vip-network
    restart: on-failure

  reservation-service:
    build: 
      context: ./backend/reservation-service # Java kodlarının bulunduğu dizin
    container_name: vip-reservation
    depends_on:
      - postgres-db
    networks:
      - vip-network
    restart: on-failure

# ==========================================
# AĞ TANIMLAMASI
# ==========================================
networks:
  vip-network:
    driver: bridge