import { StyleSheet } from 'react-native';

export function createAdminManagementStyles(theme) {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: theme.background },
    content: { padding: 16, paddingBottom: 40 },
    headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    heading: { color: theme.text, fontSize: 24, fontWeight: '800' },
    count: { color: theme.textSecondary, fontSize: 13, fontWeight: '700' },
    searchInput: {
      marginTop: 14, minHeight: 46, borderWidth: 1, borderColor: theme.border,
      borderRadius: 10, paddingHorizontal: 14, color: theme.text,
      backgroundColor: theme.inputBackground,
    },
    placeholderColor: { color: theme.placeholder },
    filterLabel: { marginTop: 14, color: theme.textSecondary, fontSize: 12, fontWeight: '800' },
    chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
    chip: {
      borderWidth: 1, borderColor: theme.border, borderRadius: 999,
      paddingHorizontal: 12, paddingVertical: 8, backgroundColor: theme.surface,
    },
    chipSelected: { borderColor: theme.accent, backgroundColor: theme.surfaceSecondary },
    chipText: { color: theme.textSecondary, fontSize: 12, fontWeight: '700' },
    chipTextSelected: { color: theme.accent },
    card: {
      marginTop: 12, borderWidth: 1, borderColor: theme.border, borderRadius: 12,
      padding: 15, backgroundColor: theme.surface,
    },
    cardTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
    cardTitleArea: { flex: 1 },
    cardTitle: { color: theme.text, fontSize: 17, fontWeight: '800' },
    cardSubtitle: { marginTop: 3, color: theme.textSecondary, fontSize: 13 },
    metadata: { marginTop: 10, gap: 5 },
    metadataText: { color: theme.textSecondary, fontSize: 13, lineHeight: 18 },
    metadataStrong: { color: theme.text, fontWeight: '700' },
    badge: { borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5 },
    badgeActive: { backgroundColor: '#DCFCE7' },
    badgePassive: { backgroundColor: '#FEE2E2' },
    badgeText: { fontSize: 11, fontWeight: '800' },
    badgeTextActive: { color: '#166534' },
    badgeTextPassive: { color: '#991B1B' },
    actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 },
    actionButton: {
      borderWidth: 1, borderColor: theme.accent, borderRadius: 8,
      paddingHorizontal: 11, paddingVertical: 9,
    },
    actionText: { color: theme.accent, fontSize: 12, fontWeight: '800' },
    dangerButton: { borderColor: theme.error },
    dangerText: { color: theme.error },
    disabled: { opacity: 0.4 },
    primaryButton: {
      marginTop: 14, alignItems: 'center', borderRadius: 9,
      paddingHorizontal: 16, paddingVertical: 12, backgroundColor: theme.accent,
    },
    primaryButtonText: { color: theme.buttonText, fontWeight: '800' },
    state: { alignItems: 'center', justifyContent: 'center', padding: 40 },
    stateTitle: { color: theme.text, fontSize: 17, fontWeight: '800', textAlign: 'center' },
    stateText: { marginTop: 8, color: theme.textSecondary, textAlign: 'center', lineHeight: 20 },
    formContent: { padding: 18, paddingBottom: 44 },
    formTitle: { color: theme.text, fontSize: 24, fontWeight: '800' },
    formSubtitle: { marginTop: 6, marginBottom: 10, color: theme.textSecondary, lineHeight: 20 },
    fieldLabel: { marginTop: 14, marginBottom: 6, color: theme.text, fontSize: 13, fontWeight: '700' },
    input: {
      minHeight: 46, borderWidth: 1, borderColor: theme.border, borderRadius: 9,
      paddingHorizontal: 12, color: theme.text, backgroundColor: theme.inputBackground,
    },
    inputError: { borderColor: theme.error },
    errorText: { marginTop: 5, color: theme.error, fontSize: 12 },
    formError: {
      marginTop: 16, borderWidth: 1, borderColor: theme.error, borderRadius: 9,
      padding: 12, color: theme.error, backgroundColor: theme.surface,
    },
  });
}
