import colors from './colors';

export const lightTheme = {
  mode: 'light',
  background: colors.background,
  surface: colors.card,
  surfaceSecondary: colors.border,
  inputBackground: colors.card,
  primary: colors.primary,
  accent: colors.accent,
  accentBright: colors.accentBright,
  accentSoft: colors.accentSoft,
  text: colors.primary,
  textSecondary: colors.muted,
  border: colors.border,
  placeholder: colors.muted,
  error: colors.warning,
  buttonText: colors.card,
  headerBackground: colors.secondary,
  headerText: colors.card,
  divider: colors.border,
  shadow: colors.primary,
  heroBackground: colors.secondary,
  heroText: colors.card,
  heroTextSecondary: '#CBD5E1',
  heroSurface: 'rgba(255, 255, 255, 0.08)',
  heroBorder: 'rgba(255, 255, 255, 0.14)',
};

export const darkTheme = {
  mode: 'dark',
  background: '#07111F',
  surface: '#0F2138',
  surfaceSecondary: '#142A45',
  inputBackground: '#0B1F34',
  primary: colors.secondary,
  accent: '#709ABD',
  accentBright: '#A8C3D8',
  accentSoft: '#173149',
  text: colors.card,
  textSecondary: colors.border,
  border: '#29415F',
  placeholder: '#7C91AA',
  error: colors.warning,
  buttonText: colors.card,
  headerBackground: colors.secondary,
  headerText: colors.card,
  divider: colors.muted,
  shadow: colors.primary,
  heroBackground: colors.secondary,
  heroText: colors.card,
  heroTextSecondary: '#CBD5E1',
  heroSurface: 'rgba(255, 255, 255, 0.08)',
  heroBorder: 'rgba(255, 255, 255, 0.14)',
};
