import { StyleSheet } from 'react-native';

export function createReservationStyles(theme) {
  return StyleSheet.create({
    safeArea: { flex: 1, overflow: 'hidden', backgroundColor: theme.background },
    decorations: { ...StyleSheet.absoluteFillObject },
    topOrb: {
      position: 'absolute',
      top: -120,
      right: -105,
      width: 270,
      height: 270,
      borderRadius: 135,
      backgroundColor: theme.surface,
      opacity: 0.38,
    },
    topRing: {
      position: 'absolute',
      top: 58,
      right: -34,
      width: 120,
      height: 120,
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 60,
      opacity: 0.18,
    },
    bottomOrb: {
      position: 'absolute',
      bottom: -140,
      left: -100,
      width: 290,
      height: 290,
      borderRadius: 145,
      backgroundColor: theme.primary,
      opacity: 0.12,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 22,
      paddingTop: 18,
      paddingBottom: 34,
    },
    stepIndicator: { flexDirection: 'row', alignItems: 'center', marginBottom: 24 },
    stepItemContainer: { flex: 1, flexDirection: 'row', alignItems: 'center' },
    stepItem: { alignItems: 'center', gap: 5 },
    stepDot: {
      width: 26,
      height: 26,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 13,
      backgroundColor: theme.surface,
    },
    completedStepDot: { borderColor: theme.accent, backgroundColor: theme.surfaceSecondary },
    activeStepDot: {
      borderColor: theme.accent,
      backgroundColor: theme.accent,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
      elevation: 3,
    },
    stepNumber: { color: theme.textSecondary, fontSize: 10, fontWeight: '800' },
    highlightedStepNumber: { color: theme.buttonText },
    stepLabel: { color: theme.textSecondary, fontSize: 10, fontWeight: '600' },
    completedStepLabel: { color: theme.textSecondary, fontWeight: '700' },
    activeStepLabel: { color: theme.accent, fontWeight: '800' },
    stepLine: {
      height: 1,
      flex: 1,
      marginHorizontal: 7,
      marginBottom: 17,
      backgroundColor: theme.divider,
    },
    completedStepLine: { backgroundColor: theme.accent, opacity: 0.55 },
    headingArea: { maxWidth: 580 },
    eyebrow: {
      color: theme.accent,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.7,
    },
    title: {
      marginTop: 9,
      color: theme.text,
      fontSize: 31,
      fontWeight: '800',
      lineHeight: 38,
      letterSpacing: -0.6,
    },
    highlightedTitle: { color: theme.accent },
    description: {
      marginTop: 10,
      color: theme.textSecondary,
      fontSize: 14,
      lineHeight: 21,
    },
    summaryCard: {
      position: 'relative',
      marginTop: 22,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 20,
      overflow: 'hidden',
      padding: 18,
      backgroundColor: theme.surface,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 4,
    },
    summaryAccent: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      width: 4,
      backgroundColor: theme.accent,
    },
    summaryHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    cardEyebrow: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 1.1,
    },
    cardTitle: { marginTop: 4, color: theme.text, fontSize: 19, fontWeight: '800' },
    passengerBadge: { alignItems: 'center' },
    passengerValue: { color: theme.accent, fontSize: 20, fontWeight: '800' },
    passengerLabel: {
      color: theme.textSecondary,
      fontSize: 7,
      fontWeight: '800',
      letterSpacing: 0.7,
    },
    routeRow: { flexDirection: 'row', marginTop: 18 },
    markerColumn: { width: 22, alignItems: 'center', paddingVertical: 5 },
    pickupMarker: {
      width: 10,
      height: 10,
      borderWidth: 2,
      borderColor: theme.accent,
      borderRadius: 5,
      backgroundColor: theme.surface,
    },
    routeLine: { width: 1, height: 35, backgroundColor: theme.divider },
    dropoffMarker: {
      width: 10,
      height: 10,
      borderWidth: 2,
      borderColor: theme.textSecondary,
      borderRadius: 3,
      backgroundColor: theme.surface,
    },
    locationColumn: { flex: 1, justifyContent: 'space-between', minHeight: 65, paddingLeft: 7 },
    locationLabel: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 0.8,
    },
    locationValue: { marginTop: 3, color: theme.text, fontSize: 13, fontWeight: '700' },
    summaryDivider: { height: 1, marginVertical: 15, backgroundColor: theme.divider },
    vehicleRow: { flexDirection: 'row', alignItems: 'center' },
    vehicleMonogram: {
      width: 43,
      height: 43,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 13,
      backgroundColor: theme.primary,
    },
    vehicleMonogramText: {
      color: theme.accent,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 1,
    },
    vehicleText: { flex: 1, minWidth: 0, marginLeft: 11 },
    vehicleLabel: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 0.8,
    },
    vehicleName: { marginTop: 4, color: theme.text, fontSize: 14, fontWeight: '800' },
    priceBox: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      marginTop: 16,
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 15,
      padding: 14,
      backgroundColor: theme.surfaceSecondary,
    },
    priceLabel: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 0.8,
    },
    priceHint: {
      maxWidth: 190,
      marginTop: 4,
      color: theme.textSecondary,
      fontSize: 9,
      lineHeight: 13,
    },
    priceValue: { color: theme.accent, fontSize: 25, fontWeight: '800' },
    currencyText: {
      marginTop: 7,
      color: theme.textSecondary,
      fontSize: 9,
      textAlign: 'right',
    },
    paymentCard: {
      marginTop: 18,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 20,
      padding: 18,
      backgroundColor: theme.surface,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 3,
    },
    paymentHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    selectedPaymentBadge: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 16,
      backgroundColor: theme.accent,
    },
    selectedPaymentIcon: { color: theme.buttonText, fontSize: 15, fontWeight: '800' },
    paymentDescription: {
      marginTop: 12,
      color: theme.textSecondary,
      fontSize: 12,
      lineHeight: 18,
    },
    paymentNotice: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      marginTop: 13,
      borderLeftWidth: 2,
      borderLeftColor: theme.accent,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: theme.surfaceSecondary,
    },
    paymentNoticeIcon: { marginTop: 2, color: theme.accent, fontSize: 8 },
    paymentNoticeText: {
      flex: 1,
      color: theme.textSecondary,
      fontSize: 9,
      lineHeight: 15,
    },
    notesLabel: {
      marginTop: 16,
      color: theme.textSecondary,
      fontSize: 11,
      fontWeight: '700',
    },
    notesInput: {
      minHeight: 90,
      marginTop: 7,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 13,
      paddingHorizontal: 13,
      paddingVertical: 12,
      backgroundColor: theme.inputBackground,
      color: theme.text,
      fontSize: 13,
      lineHeight: 19,
    },
    characterCount: {
      marginTop: 5,
      color: theme.textSecondary,
      fontSize: 9,
      textAlign: 'right',
    },
    successCard: {
      alignItems: 'center',
      marginTop: 22,
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 20,
      padding: 20,
      backgroundColor: theme.surface,
    },
    successIcon: {
      width: 52,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 26,
      backgroundColor: theme.accent,
    },
    successIconText: { color: theme.buttonText, fontSize: 24, fontWeight: '800' },
    successTitle: { marginTop: 13, color: theme.text, fontSize: 19, fontWeight: '800' },
    successDescription: {
      marginTop: 7,
      color: theme.textSecondary,
      fontSize: 11,
      lineHeight: 17,
      textAlign: 'center',
    },
    referenceBox: {
      width: '100%',
      alignItems: 'center',
      marginTop: 16,
      borderRadius: 14,
      padding: 13,
      backgroundColor: theme.surfaceSecondary,
    },
    referenceLabel: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 1,
    },
    referenceValue: {
      marginTop: 5,
      color: theme.accent,
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: 1,
    },
    errorBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginTop: 15,
      borderWidth: 1,
      borderColor: theme.error,
      borderRadius: 13,
      padding: 12,
      backgroundColor: theme.surface,
    },
    errorIcon: { color: theme.error, fontSize: 16, fontWeight: '800' },
    errorText: { flex: 1, color: theme.error, fontSize: 11, lineHeight: 16 },
    actions: { marginTop: 20, gap: 10 },
    primaryButton: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      borderRadius: 16,
      paddingHorizontal: 20,
      backgroundColor: theme.accent,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.22,
      shadowRadius: 8,
      elevation: 4,
    },
    primaryButtonText: { color: theme.buttonText, fontSize: 16, fontWeight: '800' },
    buttonArrow: { color: theme.buttonText, fontSize: 20, fontWeight: '700' },
    primaryButtonPressed: { opacity: 0.8, transform: [{ scale: 0.99 }] },
    disabledButton: { opacity: 0.55 },
    termsText: {
      color: theme.textSecondary,
      fontSize: 9,
      lineHeight: 14,
      textAlign: 'center',
    },
  });
}
