import { StyleSheet } from 'react-native';

export function createReservationLookupStyles(theme) {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: theme.background },
    keyboardView: { flex: 1 },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 22,
      paddingTop: 28,
      paddingBottom: 36,
    },
    headingArea: { maxWidth: 560 },
    eyebrow: {
      color: theme.accent,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.5,
    },
    title: {
      marginTop: 9,
      color: theme.text,
      fontSize: 29,
      fontWeight: '800',
      lineHeight: 36,
    },
    description: {
      marginTop: 10,
      color: theme.textSecondary,
      fontSize: 14,
      lineHeight: 21,
    },
    formCard: {
      marginTop: 24,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 20,
      padding: 18,
      backgroundColor: theme.surface,
    },
    label: {
      marginTop: 13,
      marginBottom: 7,
      color: theme.textSecondary,
      fontSize: 11,
      fontWeight: '700',
    },
    input: {
      minHeight: 50,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 13,
      paddingHorizontal: 13,
      backgroundColor: theme.inputBackground,
      color: theme.text,
      fontSize: 14,
    },
    inputError: { borderColor: theme.error },
    errorBox: {
      marginTop: 14,
      borderWidth: 1,
      borderColor: theme.error,
      borderRadius: 12,
      padding: 11,
      backgroundColor: theme.surfaceSecondary,
    },
    errorText: { marginTop: 5, color: theme.error, fontSize: 11, lineHeight: 16 },
    primaryButton: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      marginTop: 22,
      borderRadius: 16,
      paddingHorizontal: 18,
      backgroundColor: theme.accent,
    },
    primaryButtonText: { color: theme.buttonText, fontSize: 15, fontWeight: '800' },
    disabledButton: { opacity: 0.55 },
    pressedButton: { opacity: 0.8 },
    detailsCard: {
      marginTop: 24,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 20,
      padding: 18,
      backgroundColor: theme.surface,
    },
    codeLabel: {
      color: theme.textSecondary,
      fontSize: 9,
      fontWeight: '800',
      letterSpacing: 1.1,
      textAlign: 'center',
    },
    codeValue: {
      marginTop: 7,
      color: theme.accent,
      fontSize: 21,
      fontWeight: '800',
      letterSpacing: 1,
      textAlign: 'center',
    },
    divider: { height: 1, marginVertical: 16, backgroundColor: theme.divider },
    detailRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 16,
      paddingVertical: 8,
    },
    detailLabel: { flex: 0.4, color: theme.textSecondary, fontSize: 11 },
    detailValue: {
      flex: 0.6,
      color: theme.text,
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'right',
    },
  });
}
