import { StyleSheet } from 'react-native';

export function createTransferSearchStyles(theme) {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: theme.background },
    keyboardView: { flex: 1, backgroundColor: theme.background },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 22,
      paddingTop: 18,
      paddingBottom: 32,
      backgroundColor: theme.background,
    },
    stepIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 22,
    },
    stepItemContainer: { flex: 1, flexDirection: 'row', alignItems: 'center' },
    stepItem: { alignItems: 'center', gap: 5 },
    stepDot: {
      width: 24,
      height: 24,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      backgroundColor: theme.surface,
    },
    activeStepDot: { borderColor: theme.accent, backgroundColor: theme.accent },
    stepNumber: { color: theme.textSecondary, fontSize: 10, fontWeight: '700' },
    activeStepNumber: { color: theme.buttonText },
    stepLabel: { color: theme.textSecondary, fontSize: 10, fontWeight: '600' },
    activeStepLabel: { color: theme.accent, fontWeight: '800' },
    stepLine: { height: 1, flex: 1, marginHorizontal: 7, marginBottom: 17, backgroundColor: theme.divider },
    headingTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
    headingArea: { flex: 1, maxWidth: 560 },
    eyebrow: { color: theme.accent, fontSize: 10, fontWeight: '800', letterSpacing: 1.6 },
    title: { marginTop: 8, color: theme.text, fontSize: 29, fontWeight: '800', lineHeight: 36, letterSpacing: -0.4 },
    description: { marginTop: 8, color: theme.textSecondary, fontSize: 14, lineHeight: 21 },
    settingsButton: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 13,
      backgroundColor: theme.surface,
    },
    settingsIcon: { color: theme.accent, fontSize: 19 },
    routeCard: {
      marginTop: 22,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 18,
      padding: 18,
      backgroundColor: theme.surface,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 4,
    },
    cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 18 },
    cardEyebrow: { color: theme.textSecondary, fontSize: 9, fontWeight: '700', letterSpacing: 1.2 },
    cardTitle: { marginTop: 3, color: theme.text, fontSize: 20, fontWeight: '800' },
    swapButton: {
      minHeight: 38,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 19,
      paddingHorizontal: 12,
      backgroundColor: theme.surface,
    },
    swapIcon: { color: theme.accent, fontSize: 17, fontWeight: '800' },
    swapButtonText: { color: theme.accent, fontSize: 12, fontWeight: '800' },
    routeFields: { position: 'relative' },
    routeConnector: {
      position: 'absolute',
      top: 25,
      bottom: 25,
      left: 7,
      width: 1,
      backgroundColor: theme.divider,
    },
    routeFieldRow: { flexDirection: 'row', alignItems: 'flex-start' },
    routeMarkerColumn: { width: 28, alignItems: 'flex-start', paddingTop: 20 },
    routeMarker: { width: 15, height: 15, borderWidth: 3, borderRadius: 8 },
    pickupMarker: { borderColor: theme.accent, backgroundColor: theme.surface },
    dropoffMarker: { borderColor: theme.textSecondary, borderRadius: 4, backgroundColor: theme.surface },
    routeFieldContent: { flex: 1, minWidth: 0 },
    routeLabel: { marginBottom: 5, color: theme.textSecondary, fontSize: 11, fontWeight: '700', letterSpacing: 0.4 },
    routeInput: {
      minHeight: 46,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      paddingHorizontal: 13,
      backgroundColor: theme.inputBackground,
      color: theme.text,
      fontSize: 15,
      fontWeight: '600',
    },
    activeRouteInput: { borderColor: theme.accent, borderWidth: 1.5 },
    routeAddress: { marginTop: 6, color: theme.textSecondary, fontSize: 11, lineHeight: 16 },
    routeDivider: { height: 1, marginVertical: 14, marginLeft: 28, backgroundColor: theme.divider },
    inputError: { borderColor: theme.error },
    errorText: { marginTop: 5, color: theme.error, fontSize: 11, lineHeight: 16 },
    searchStatus: { marginTop: 7, color: theme.textSecondary, fontSize: 11, lineHeight: 17 },
    suggestionList: {
      marginTop: 8,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: theme.surfaceSecondary,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 5,
    },
    suggestionItem: { minHeight: 58, justifyContent: 'center', paddingHorizontal: 14, paddingVertical: 10 },
    suggestionDivider: { borderBottomWidth: 1, borderBottomColor: theme.divider },
    suggestionName: { color: theme.text, fontSize: 14, fontWeight: '700' },
    suggestionAddress: { marginTop: 3, color: theme.textSecondary, fontSize: 11, lineHeight: 16 },
    infoGrid: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginTop: 18 },
    infoCardWrapper: { flex: 1 },
    infoCard: {
      minHeight: 82,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 13,
      backgroundColor: theme.surface,
    },
    selectedInfoCard: { borderColor: theme.accent },
    infoIcon: { color: theme.accent, fontSize: 19 },
    infoCardText: { flex: 1, minWidth: 0 },
    infoLabel: { color: theme.textSecondary, fontSize: 10, fontWeight: '700', letterSpacing: 0.5 },
    infoValue: { marginTop: 5, color: theme.text, fontSize: 14, fontWeight: '700', lineHeight: 18 },
    infoPlaceholder: { marginTop: 5, color: theme.placeholder, fontSize: 14, fontWeight: '600' },
    pickerArea: {
      alignItems: 'flex-end',
      marginTop: 10,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 14,
      padding: 8,
      backgroundColor: theme.surface,
    },
    pickerDoneButton: { minHeight: 40, justifyContent: 'center', paddingHorizontal: 12 },
    pickerDoneText: { color: theme.accent, fontSize: 14, fontWeight: '800' },
    passengerCard: {
      minHeight: 78,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 12,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 16,
      paddingHorizontal: 16,
      backgroundColor: theme.surface,
    },
    passengerHeading: { flexDirection: 'row', alignItems: 'center', gap: 11 },
    passengerValue: { marginTop: 4, color: theme.text, fontSize: 15, fontWeight: '700' },
    compactCounter: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    counterButton: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      backgroundColor: theme.surfaceSecondary,
    },
    counterButtonText: { color: theme.accent, fontSize: 21, fontWeight: '700', lineHeight: 24 },
    counterValue: { minWidth: 20, color: theme.text, fontSize: 16, fontWeight: '800', textAlign: 'center' },
    summaryCard: {
      flexDirection: 'row',
      marginTop: 18,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: theme.surface,
    },
    summaryAccent: { width: 4, backgroundColor: theme.accent },
    summaryContent: { flex: 1, paddingHorizontal: 16, paddingVertical: 15 },
    summaryTitle: { color: theme.text, fontSize: 15, fontWeight: '800' },
    summaryRoute: { marginTop: 9, color: theme.text, fontSize: 14, fontWeight: '700', lineHeight: 20 },
    summaryDetails: { marginTop: 5, color: theme.textSecondary, fontSize: 12, lineHeight: 17 },
    summaryEmpty: { marginTop: 8, color: theme.textSecondary, fontSize: 12, lineHeight: 18 },
    summaryInfo: { marginTop: 10, color: theme.textSecondary, fontSize: 11, lineHeight: 17 },
    continueButton: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      marginTop: 20,
      borderRadius: 14,
      paddingHorizontal: 20,
      backgroundColor: theme.accent,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    continueButtonText: { color: theme.buttonText, fontSize: 16, fontWeight: '800' },
    continueArrow: { color: theme.buttonText, fontSize: 20, fontWeight: '700' },
    continueButtonPressed: { opacity: 0.78, transform: [{ scale: 0.99 }] },
    pressed: { opacity: 0.72 },
    disabled: { opacity: 0.35 },
  });
}
