import { StyleSheet } from 'react-native';

export function createVehicleSelectionStyles(theme) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 22,
      paddingTop: 18,
      paddingBottom: 32,
      backgroundColor: theme.background,
    },
    centered: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: 16,
    },
    stepIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 22,
    },
    stepItemContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    stepItem: {
      alignItems: 'center',
      gap: 5,
    },
    stepDot: {
      width: 24,
      height: 24,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      backgroundColor: theme.surface,
    },
    activeStepDot: {
      borderColor: theme.accent,
      backgroundColor: theme.accent,
    },
    completedStepDot: {
      borderColor: theme.accent,
      backgroundColor: theme.surface,
    },
    stepNumber: {
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '700',
    },
    activeStepNumber: {
      color: theme.buttonText,
    },
    completedStepNumber: {
      color: theme.accent,
    },
    stepLabel: {
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '600',
    },
    activeStepLabel: {
      color: theme.accent,
      fontWeight: '800',
    },
    stepLine: {
      height: 1,
      flex: 1,
      marginHorizontal: 7,
      marginBottom: 17,
      backgroundColor: theme.divider,
    },
    headingArea: {
      maxWidth: 560,
    },
    eyebrow: {
      color: theme.accent,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.6,
    },
    title: {
      marginTop: 8,
      color: theme.text,
      fontSize: 26,
      fontWeight: '800',
      lineHeight: 33,
      letterSpacing: -0.4,
    },
    description: {
      marginTop: 8,
      color: theme.textSecondary,
      fontSize: 14,
      lineHeight: 21,
    },
    routeSummaryCard: {
      flexDirection: 'row',
      marginTop: 20,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: theme.surface,
    },
    routeSummaryAccent: {
      width: 4,
      backgroundColor: theme.accent,
    },
    routeSummaryContent: {
      flex: 1,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    routeSummaryRoute: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 20,
    },
    routeSummaryDetails: {
      marginTop: 6,
      color: theme.textSecondary,
      fontSize: 12,
      lineHeight: 17,
    },
    errorText: {
      color: theme.error,
      fontSize: 15,
      textAlign: 'center',
    },
    fieldErrorText: {
      marginTop: 5,
      color: theme.error,
      fontSize: 12,
      lineHeight: 17,
    },
    retryButton: {
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      paddingHorizontal: 20,
      backgroundColor: theme.accent,
    },
    retryButtonText: {
      color: theme.buttonText,
      fontSize: 15,
      fontWeight: '700',
    },
    vehicleList: {
      marginTop: 20,
      gap: 14,
    },
    vehicleCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 16,
      padding: 16,
      backgroundColor: theme.surface,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    vehicleCardSelected: {
      borderColor: theme.accent,
      borderWidth: 2,
    },
    vehicleIconBox: {
      width: 52,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 14,
      backgroundColor: theme.surfaceSecondary,
    },
    vehicleIcon: {
      color: theme.accent,
      fontSize: 24,
    },
    vehicleInfo: {
      flex: 1,
      minWidth: 0,
    },
    vehicleName: {
      color: theme.text,
      fontSize: 16,
      fontWeight: '800',
    },
    vehicleMeta: {
      marginTop: 4,
      color: theme.textSecondary,
      fontSize: 12,
      lineHeight: 17,
    },
    vehiclePrice: {
      marginTop: 8,
      color: theme.accent,
      fontSize: 15,
      fontWeight: '800',
    },
    selectionMark: {
      width: 24,
      height: 24,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
    },
    selectedMark: {
      borderColor: theme.accent,
      backgroundColor: theme.accent,
    },
    checkText: {
      color: theme.buttonText,
      fontSize: 14,
      fontWeight: '800',
    },
    continueButton: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      marginTop: 24,
      borderRadius: 14,
      paddingHorizontal: 20,
      backgroundColor: theme.accent,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    continueButtonText: {
      color: theme.buttonText,
      fontSize: 16,
      fontWeight: '800',
    },
    continueArrow: {
      color: theme.buttonText,
      fontSize: 20,
      fontWeight: '700',
    },
    continueButtonPressed: {
      opacity: 0.78,
      transform: [{ scale: 0.99 }],
    },
    disabled: {
      opacity: 0.35,
    },
    pressed: {
      opacity: 0.72,
    },
  });
}