import { StyleSheet } from 'react-native';

export function createVehicleSelectionStyles(theme) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      overflow: 'hidden',
      backgroundColor: theme.background,
    },
    decorations: {
      ...StyleSheet.absoluteFillObject,
    },
    topOrb: {
      position: 'absolute',
      top: -120,
      right: -100,
      width: 270,
      height: 270,
      borderRadius: 135,
      backgroundColor: theme.surface,
      opacity: 0.38,
    },
    topRing: {
      position: 'absolute',
      top: 54,
      right: -35,
      width: 124,
      height: 124,
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 62,
      opacity: 0.18,
    },
    bottomOrb: {
      position: 'absolute',
      bottom: -150,
      left: -110,
      width: 300,
      height: 300,
      borderRadius: 150,
      backgroundColor: theme.primary,
      opacity: 0.12,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 22,
      paddingTop: 18,
      paddingBottom: 132,
    },
    stepIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 24,
    },
    stepItemContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    stepItem: {
      alignItems: 'center',
      gap: 5,
    },
    stepDot: {
      width: 26,
      height: 26,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 13,
      backgroundColor: theme.surface,
    },
    completedStepDot: {
      borderColor: theme.accent,
      backgroundColor: theme.surfaceSecondary,
    },
    activeStepDot: {
      borderColor: theme.accent,
      backgroundColor: theme.accent,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
      elevation: 3,
    },
    stepNumber: {
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '800',
    },
    highlightedStepNumber: {
      color: theme.buttonText,
    },
    stepLabel: {
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '600',
    },
    completedStepLabel: {
      color: theme.textSecondary,
      fontWeight: '700',
    },
    activeStepLabel: {
      color: theme.accent,
      fontWeight: '800',
    },
    stepLine: {
      height: 1,
      flex: 1,
      marginHorizontal: 7,
      marginBottom: 17,
      backgroundColor: theme.divider,
    },
    completedStepLine: {
      backgroundColor: theme.accent,
      opacity: 0.55,
    },
    headingArea: {
      maxWidth: 580,
    },
    eyebrow: {
      color: theme.accent,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.7,
    },
    title: {
      marginTop: 9,
      color: theme.text,
      fontSize: 32,
      fontWeight: '800',
      lineHeight: 39,
      letterSpacing: -0.6,
    },
    highlightedTitle: {
      color: theme.accent,
    },
    description: {
      marginTop: 10,
      color: theme.textSecondary,
      fontSize: 14,
      lineHeight: 21,
    },
    tripSummary: {
      position: 'relative',
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 22,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 18,
      overflow: 'hidden',
      paddingHorizontal: 17,
      paddingVertical: 15,
      backgroundColor: theme.surface,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.11,
      shadowRadius: 10,
      elevation: 3,
    },
    summaryAccent: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      width: 4,
      backgroundColor: theme.accent,
    },
    summaryRoute: {
      flex: 1,
      minWidth: 0,
    },
    summaryEyebrow: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 1.1,
    },
    routeRow: {
      flexDirection: 'row',
      marginTop: 9,
    },
    routeMarkerColumn: {
      width: 20,
      alignItems: 'center',
      paddingVertical: 4,
    },
    pickupMarker: {
      width: 9,
      height: 9,
      borderWidth: 2,
      borderColor: theme.accent,
      borderRadius: 5,
      backgroundColor: theme.surface,
    },
    routeLine: {
      width: 1,
      height: 21,
      backgroundColor: theme.divider,
    },
    dropoffMarker: {
      width: 9,
      height: 9,
      borderWidth: 2,
      borderColor: theme.textSecondary,
      borderRadius: 3,
      backgroundColor: theme.surface,
    },
    routeNames: {
      flex: 1,
      justifyContent: 'space-between',
      minHeight: 48,
      paddingLeft: 6,
    },
    routeName: {
      color: theme.text,
      fontSize: 12,
      fontWeight: '700',
    },
    tripMeta: {
      alignItems: 'center',
      marginLeft: 12,
      borderLeftWidth: 1,
      borderLeftColor: theme.divider,
      paddingLeft: 15,
    },
    tripMetaValue: {
      color: theme.accent,
      fontSize: 22,
      fontWeight: '800',
    },
    tripMetaLabel: {
      marginTop: 2,
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 0.8,
    },
    listHeader: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      marginTop: 28,
      marginBottom: 12,
    },
    sectionEyebrow: {
      color: theme.textSecondary,
      fontSize: 9,
      fontWeight: '800',
      letterSpacing: 1.2,
    },
    sectionTitle: {
      marginTop: 4,
      color: theme.text,
      fontSize: 20,
      fontWeight: '800',
    },
    vehicleCount: {
      color: theme.accent,
      fontSize: 11,
      fontWeight: '800',
    },
    vehicleList: {
      gap: 14,
    },
    vehicleCardWrapper: {
      width: '100%',
    },
    vehicleCard: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 20,
      overflow: 'hidden',
      backgroundColor: theme.surface,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 4,
    },
    selectedVehicleCard: {
      borderWidth: 2,
      borderColor: theme.accent,
      shadowOpacity: 0.2,
      elevation: 7,
    },
    unavailableVehicleCard: {
      opacity: 0.48,
    },
    pressedCard: {
      opacity: 0.86,
    },
    imageArea: {
      position: 'relative',
      height: 166,
      overflow: 'hidden',
      backgroundColor: theme.surfaceSecondary,
    },
    vehicleImage: {
      width: '100%',
      height: '100%',
    },
    imageFallback: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.mode === 'light' ? theme.surfaceSecondary : theme.primary,
    },
    imageFallbackIcon: {
      color: theme.accent,
      fontSize: 25,
      fontWeight: '800',
      letterSpacing: 3,
    },
    imageFallbackText: {
      marginTop: 7,
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 1.1,
      textTransform: 'uppercase',
    },
    classBadge: {
      position: 'absolute',
      top: 12,
      left: 12,
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: theme.primary,
    },
    classBadgeText: {
      color: theme.accent,
      fontSize: 9,
      fontWeight: '800',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    selectedBadge: {
      position: 'absolute',
      top: 12,
      right: 12,
      width: 31,
      height: 31,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 16,
      backgroundColor: theme.accent,
    },
    selectedBadgeIcon: {
      color: theme.buttonText,
      fontSize: 16,
      fontWeight: '800',
    },
    vehicleContent: {
      padding: 17,
    },
    vehicleHeading: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
    },
    vehicleNameArea: {
      flex: 1,
      minWidth: 0,
    },
    vehicleBrand: {
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    vehicleModel: {
      marginTop: 4,
      color: theme.text,
      fontSize: 20,
      fontWeight: '800',
    },
    priceArea: {
      alignItems: 'flex-end',
    },
    priceLabel: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 0.8,
    },
    priceValue: {
      marginTop: 3,
      color: theme.accent,
      fontSize: 21,
      fontWeight: '800',
    },
    vehicleDetails: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 15,
    },
    detailPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 12,
      paddingHorizontal: 9,
      paddingVertical: 7,
      backgroundColor: theme.surfaceSecondary,
    },
    detailIcon: {
      color: theme.accent,
      fontSize: 8,
    },
    detailText: {
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '700',
    },
    cardFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 15,
      borderTopWidth: 1,
      borderTopColor: theme.divider,
      paddingTop: 13,
    },
    availabilityText: {
      flex: 1,
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '600',
    },
    unavailableText: {
      color: theme.error,
    },
    selectText: {
      marginLeft: 10,
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1,
    },
    selectedText: {
      color: theme.accent,
    },
    stateCard: {
      alignItems: 'center',
      marginTop: 6,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 20,
      paddingHorizontal: 26,
      paddingVertical: 34,
      backgroundColor: theme.surface,
    },
    stateIcon: {
      width: 50,
      height: 50,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 16,
      backgroundColor: theme.surfaceSecondary,
    },
    stateIconText: {
      color: theme.accent,
      fontSize: 13,
      fontWeight: '800',
    },
    stateTitle: {
      marginTop: 15,
      color: theme.text,
      fontSize: 17,
      fontWeight: '800',
      textAlign: 'center',
    },
    stateDescription: {
      marginTop: 7,
      color: theme.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      textAlign: 'center',
    },
    retryButton: {
      marginTop: 17,
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 13,
      paddingHorizontal: 18,
      paddingVertical: 11,
    },
    retryButtonText: {
      color: theme.accent,
      fontSize: 12,
      fontWeight: '800',
    },
    footer: {
      position: 'absolute',
      right: 0,
      bottom: 0,
      left: 0,
      borderTopWidth: 1,
      borderTopColor: theme.border,
      paddingHorizontal: 22,
      paddingTop: 12,
      paddingBottom: 17,
      backgroundColor: theme.surface,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 10,
    },
    continueButton: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      borderRadius: 16,
      paddingHorizontal: 20,
      backgroundColor: theme.accent,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.22,
      shadowRadius: 8,
      elevation: 4,
    },
    continueButtonDisabled: {
      opacity: 0.42,
      shadowOpacity: 0,
      elevation: 0,
    },
    continueButtonPressed: {
      opacity: 0.8,
      transform: [{ scale: 0.99 }],
    },
    continueButtonText: {
      color: theme.buttonText,
      fontSize: 16,
      fontWeight: '800',
    },
    continueArrow: {
      color: theme.buttonText,
      fontSize: 20,
      fontWeight: '700',
    },
    footerHint: {
      marginBottom: 8,
      color: theme.textSecondary,
      fontSize: 10,
      textAlign: 'center',
    },
    pressed: {
      opacity: 0.72,
    },
  });
}
