import { StyleSheet } from 'react-native';

export function createWelcomeStyles(theme) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      overflow: 'hidden',
      backgroundColor: theme.background,
    },
    decorations: {
      ...StyleSheet.absoluteFillObject,
    },
    topOrb: {
      position: 'absolute',
      top: -110,
      right: -90,
      width: 260,
      height: 260,
      borderRadius: 130,
      backgroundColor: theme.surface,
      opacity: 0.34,
    },
    topRing: {
      position: 'absolute',
      top: 70,
      right: -28,
      width: 116,
      height: 116,
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 58,
      opacity: 0.2,
    },
    bottomOrb: {
      position: 'absolute',
      bottom: -130,
      left: -100,
      width: 280,
      height: 280,
      borderRadius: 140,
      backgroundColor: theme.primary,
      opacity: 0.16,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 22,
      paddingTop: 18,
      paddingBottom: 24,
    },
    headerTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    brandArea: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    logoPlaceholder: {
      width: 52,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 16,
      backgroundColor: theme.surface,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 8,
      elevation: 3,
    },
    logoText: {
      color: theme.accent,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: 1.7,
    },
    brandName: {
      color: theme.text,
      fontSize: 18,
      fontWeight: '800',
      letterSpacing: 0.2,
    },
    brandTagline: {
      marginTop: 3,
      color: theme.accent,
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 1.7,
    },
    settingsButton: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 22,
      backgroundColor: theme.surface,
      opacity: 0.92,
    },
    settingsIcon: {
      color: theme.accent,
      fontSize: 19,
    },
    messageArea: {
      maxWidth: 560,
      marginTop: 34,
    },
    eyebrow: {
      marginBottom: 10,
      color: theme.accent,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.7,
    },
    title: {
      color: theme.text,
      fontSize: 38,
      fontWeight: '800',
      lineHeight: 44,
      letterSpacing: -0.8,
    },
    highlightedTitle: {
      color: theme.accent,
    },
    description: {
      maxWidth: 540,
      marginTop: 16,
      color: theme.textSecondary,
      fontSize: 15,
      lineHeight: 23,
    },
    transferCard: {
      position: 'relative',
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 24,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 20,
      overflow: 'hidden',
      paddingTop: 18,
      paddingHorizontal: 18,
      backgroundColor: theme.surface,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.14,
      shadowRadius: 12,
      elevation: 4,
    },
    cardAccent: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      width: 4,
      backgroundColor: theme.accent,
    },
    routeArea: {
      flex: 1,
      minWidth: 190,
    },
    cardEyebrow: {
      color: theme.textSecondary,
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 1.2,
    },
    routeRow: {
      flexDirection: 'row',
      marginTop: 13,
    },
    routeMarkerColumn: {
      width: 25,
      alignItems: 'center',
      paddingVertical: 4,
    },
    startMarker: {
      width: 11,
      height: 11,
      borderWidth: 3,
      borderColor: theme.accent,
      borderRadius: 6,
      backgroundColor: theme.surface,
    },
    routeLine: {
      width: 1,
      height: 28,
      backgroundColor: theme.divider,
    },
    endMarker: {
      width: 11,
      height: 11,
      borderWidth: 2,
      borderColor: theme.textSecondary,
      borderRadius: 3,
      backgroundColor: theme.surface,
    },
    routeNames: {
      justifyContent: 'space-between',
      minHeight: 66,
      paddingLeft: 7,
    },
    routeLabel: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '700',
      letterSpacing: 0.8,
    },
    routeValue: {
      marginTop: 2,
      color: theme.text,
      fontSize: 14,
      fontWeight: '700',
    },
    serviceInfo: {
      alignItems: 'flex-end',
      paddingLeft: 12,
    },
    serviceBadge: {
      color: theme.accent,
      fontSize: 20,
      fontWeight: '800',
    },
    serviceLabel: {
      marginTop: 2,
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '700',
    },
    cardFooter: {
      width: '100%',
      marginTop: 15,
      borderTopWidth: 1,
      borderTopColor: theme.divider,
      paddingVertical: 12,
    },
    cardFooterText: {
      color: theme.textSecondary,
      fontSize: 10,
      lineHeight: 15,
      textAlign: 'center',
    },
    featuresArea: {
      marginTop: 24,
    },
    sectionLabel: {
      marginBottom: 10,
      color: theme.textSecondary,
      fontSize: 9,
      fontWeight: '800',
      letterSpacing: 1.3,
    },
    featuresList: {
      gap: 9,
    },
    featureAnimatedWrapper: {
      width: '100%',
    },
    featureCard: {
      minHeight: 62,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 15,
      paddingHorizontal: 14,
      paddingVertical: 10,
      backgroundColor: theme.surface,
    },
    featureIconBox: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 11,
      backgroundColor: theme.surfaceSecondary,
    },
    featureIcon: {
      color: theme.accent,
      fontSize: 15,
      fontWeight: '800',
    },
    featureTextArea: {
      flex: 1,
      marginLeft: 12,
    },
    featureTitle: {
      color: theme.text,
      fontSize: 13,
      fontWeight: '700',
    },
    featureDescription: {
      marginTop: 3,
      color: theme.textSecondary,
      fontSize: 11,
      lineHeight: 15,
    },
    footer: {
      marginTop: 24,
      gap: 17,
    },
    actions: {
      gap: 11,
    },
    button: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 16,
      paddingHorizontal: 20,
      paddingVertical: 15,
    },
    primaryButton: {
      gap: 10,
      backgroundColor: theme.accent,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.22,
      shadowRadius: 8,
      elevation: 4,
    },
    secondaryButton: {
      borderWidth: 1,
      borderColor: theme.accent,
      backgroundColor: theme.surface,
    },
    primaryButtonText: {
      color: theme.buttonText,
      fontSize: 16,
      fontWeight: '800',
    },
    buttonArrow: {
      color: theme.buttonText,
      fontSize: 20,
      fontWeight: '700',
    },
    secondaryButtonText: {
      color: theme.accent,
      fontSize: 15,
      fontWeight: '800',
    },
    primaryButtonPressed: {
      opacity: 0.78,
      transform: [{ scale: 0.99 }],
    },
    secondaryButtonPressed: {
      opacity: 0.7,
      transform: [{ translateY: 1 }],
    },
    pressed: {
      opacity: 0.7,
    },
    trustText: {
      color: theme.textSecondary,
      fontSize: 10,
      lineHeight: 16,
      textAlign: 'center',
    },
  });
}
