events {
    worker_connections 1024;
}

http {
    # YÜK DENGELEME (LOAD BALANCING) TANIMI
    # Gelen istekler bu iki backend kopyasına sırayla (Round Robin algoritmasıyla) dağıtılacak
    upstream backend_servers {
        server vip-backend-1:8080;
        server vip-backend-2:8080;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend_servers/; # İstekleri yukarıdaki gruba yönlendir
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}