events {
    worker_connections 1024;
}

http {
    # İzole ağda çalışacak olan monolitik backend servisimizin adresi
    upstream backend_api {
        server vip-backend:8080; 
    }

    server {
        listen 80;

        # Gelen tüm /api ile başlayan istekleri izole ağdaki backend-service'e yönlendir
        location /api/ {
            proxy_pass http://backend_api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}