import { StyleSheet } from 'react-native';

export function createGuestInfoStyles(theme) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      overflow: 'hidden',
      backgroundColor: theme.background,
    },
    keyboardView: {
      flex: 1,
    },
    decorations: {
      ...StyleSheet.absoluteFillObject,
    },
    topOrb: {
      position: 'absolute',
      top: -120,
      right: -105,
      width: 270,
      height: 270,
      borderRadius: 135,
      backgroundColor: theme.surface,
      opacity: 0.38,
    },
    topRing: {
      position: 'absolute',
      top: 58,
      right: -34,
      width: 120,
      height: 120,
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 60,
      opacity: 0.18,
    },
    bottomOrb: {
      position: 'absolute',
      bottom: -140,
      left: -100,
      width: 290,
      height: 290,
      borderRadius: 145,
      backgroundColor: theme.primary,
      opacity: 0.12,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 22,
      paddingTop: 18,
      paddingBottom: 32,
    },
    stepIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 24,
    },
    stepItemContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    stepItem: {
      alignItems: 'center',
      gap: 5,
    },
    stepDot: {
      width: 26,
      height: 26,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 13,
      backgroundColor: theme.surface,
    },
    completedStepDot: {
      borderColor: theme.accent,
      backgroundColor: theme.surfaceSecondary,
    },
    activeStepDot: {
      borderColor: theme.accent,
      backgroundColor: theme.accent,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
      elevation: 3,
    },
    stepNumber: {
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '800',
    },
    highlightedStepNumber: {
      color: theme.buttonText,
    },
    stepLabel: {
      color: theme.textSecondary,
      fontSize: 10,
      fontWeight: '600',
    },
    completedStepLabel: {
      color: theme.textSecondary,
      fontWeight: '700',
    },
    activeStepLabel: {
      color: theme.accent,
      fontWeight: '800',
    },
    stepLine: {
      height: 1,
      flex: 1,
      marginHorizontal: 7,
      marginBottom: 17,
      backgroundColor: theme.divider,
    },
    completedStepLine: {
      backgroundColor: theme.accent,
      opacity: 0.55,
    },
    headingArea: {
      maxWidth: 580,
    },
    eyebrow: {
      color: theme.accent,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.7,
    },
    title: {
      marginTop: 9,
      color: theme.text,
      fontSize: 31,
      fontWeight: '800',
      lineHeight: 38,
      letterSpacing: -0.6,
    },
    highlightedTitle: {
      color: theme.accent,
    },
    description: {
      marginTop: 10,
      color: theme.textSecondary,
      fontSize: 14,
      lineHeight: 21,
    },
    bookingSummary: {
      position: 'relative',
      marginTop: 22,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 18,
      overflow: 'hidden',
      padding: 17,
      backgroundColor: theme.surface,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.11,
      shadowRadius: 10,
      elevation: 3,
    },
    summaryAccent: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      width: 4,
      backgroundColor: theme.accent,
    },
    summaryEyebrow: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 1.1,
    },
    summaryRouteRow: {
      flexDirection: 'row',
      marginTop: 10,
    },
    summaryMarkerColumn: {
      width: 20,
      alignItems: 'center',
      paddingVertical: 4,
    },
    pickupMarker: {
      width: 9,
      height: 9,
      borderWidth: 2,
      borderColor: theme.accent,
      borderRadius: 5,
      backgroundColor: theme.surface,
    },
    summaryRouteLine: {
      width: 1,
      height: 21,
      backgroundColor: theme.divider,
    },
    dropoffMarker: {
      width: 9,
      height: 9,
      borderWidth: 2,
      borderColor: theme.textSecondary,
      borderRadius: 3,
      backgroundColor: theme.surface,
    },
    summaryLocations: {
      flex: 1,
      justifyContent: 'space-between',
      minHeight: 48,
      paddingLeft: 6,
    },
    summaryLocation: {
      color: theme.text,
      fontSize: 12,
      fontWeight: '700',
    },
    summaryDivider: {
      height: 1,
      marginVertical: 13,
      backgroundColor: theme.divider,
    },
    vehicleSummaryRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    vehicleMonogram: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.accent,
      borderRadius: 13,
      backgroundColor: theme.primary,
    },
    vehicleMonogramText: {
      color: theme.accent,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 1,
    },
    vehicleSummaryText: {
      flex: 1,
      minWidth: 0,
      marginLeft: 11,
    },
    vehicleSummaryLabel: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 0.8,
    },
    vehicleSummaryName: {
      marginTop: 4,
      color: theme.text,
      fontSize: 14,
      fontWeight: '800',
    },
    passengerBadge: {
      alignItems: 'center',
      marginLeft: 10,
    },
    passengerBadgeValue: {
      color: theme.accent,
      fontSize: 18,
      fontWeight: '800',
    },
    passengerBadgeLabel: {
      color: theme.textSecondary,
      fontSize: 7,
      fontWeight: '800',
      letterSpacing: 0.6,
    },
    formCard: {
      marginTop: 18,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 20,
      padding: 18,
      backgroundColor: theme.surface,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 4,
      gap: 15,
    },
    formHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 2,
    },
    formEyebrow: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 1,
    },
    formTitle: {
      marginTop: 4,
      color: theme.text,
      fontSize: 19,
      fontWeight: '800',
    },
    secureBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 12,
      paddingHorizontal: 9,
      paddingVertical: 6,
      backgroundColor: theme.surfaceSecondary,
    },
    secureBadgeIcon: {
      color: theme.accent,
      fontSize: 10,
      fontWeight: '800',
    },
    secureBadgeText: {
      color: theme.textSecondary,
      fontSize: 8,
      fontWeight: '800',
      letterSpacing: 0.7,
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 11,
    },
    nameField: {
      flex: 1,
      minWidth: 0,
    },
    fieldGroup: {
      gap: 7,
    },
    label: {
      color: theme.textSecondary,
      fontSize: 11,
      fontWeight: '700',
    },
    input: {
      minHeight: 52,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 13,
      paddingHorizontal: 14,
      backgroundColor: theme.inputBackground,
      color: theme.text,
      fontSize: 14,
      fontWeight: '600',
    },
    inputError: {
      borderColor: theme.error,
    },
    errorText: {
      color: theme.error,
      fontSize: 10,
      lineHeight: 15,
    },
    privacyBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 9,
      borderLeftWidth: 2,
      borderLeftColor: theme.accent,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 11,
      backgroundColor: theme.surfaceSecondary,
    },
    privacyIcon: {
      marginTop: 2,
      color: theme.accent,
      fontSize: 9,
    },
    privacyText: {
      flex: 1,
      color: theme.textSecondary,
      fontSize: 10,
      lineHeight: 16,
    },
    actions: {
      marginTop: 20,
      gap: 15,
    },
    continueButton: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      borderRadius: 16,
      paddingHorizontal: 20,
      backgroundColor: theme.accent,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.22,
      shadowRadius: 8,
      elevation: 4,
    },
    continueButtonText: {
      color: theme.buttonText,
      fontSize: 16,
      fontWeight: '800',
    },
    continueArrow: {
      color: theme.buttonText,
      fontSize: 20,
      fontWeight: '700',
    },
    continueButtonPressed: {
      opacity: 0.8,
      transform: [{ scale: 0.99 }],
    },
    disabledButton: {
      opacity: 0.55,
    },
    loginArea: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    loginPrompt: {
      color: theme.textSecondary,
      fontSize: 13,
    },
    loginLink: {
      color: theme.accent,
      fontSize: 13,
      fontWeight: '800',
    },
    pressed: {
      opacity: 0.72,
    },
  });
}
