export const DEFAULT_LANGUAGE = 'tr';
export const SUPPORTED_LANGUAGES = ['tr', 'en'];

export const LANGUAGE_OPTIONS = [
  { code: 'tr', label: 'Türkçe', nativeLabel: 'Türkçe' },
  { code: 'en', label: 'English', nativeLabel: 'English' },
];

export const resources = {
  tr: {
    'common.selected': 'seçili',
    'common.retry': 'Tekrar dene',
    'nav.login': 'Giriş Yap',
    'nav.transferSearch': 'Transfer Planla',
    'nav.appearance': 'Görünüm Ayarları',
    'nav.language': 'Dil Seçimi',
    'nav.notifications': 'Bildirim Tercihleri',
    'nav.emailVerification': 'E-posta Doğrulama',
    'nav.vehicleSelection': 'Araç Seçimi',
    'nav.guestInfo': 'Misafir Bilgileri',
    'nav.reservation': 'Rezervasyon ve Ödeme',
    'nav.reservations': 'Rezervasyonlarım',
    'nav.reservationLookup': 'Rezervasyonumu Görüntüle',
    'nav.reservationDetails': 'Rezervasyon Detayları',
    'settings.theme.title': 'Tema Seçimi',
    'settings.theme.description': 'Uygulamanın görünümünü tercihinize göre seçin.',
    'settings.theme.light': 'Açık Tema',
    'settings.theme.dark': 'Koyu Tema',
    'settings.theme.saved': 'Tema tercihiniz bu cihazda saklanır.',
    'settings.theme.warning': 'Tema uygulandı, ancak cihaz tercihi kaydedilemedi.',
    'settings.language.open': 'Uygulama Dili',
    'settings.language.current': 'Seçili dil: {{language}}',
    'settings.language.title': 'Dil Seçimi',
    'settings.language.description': 'Uygulamada görmek istediğiniz dili seçin.',
    'settings.language.saved': 'Dil tercihiniz bu cihazda saklanır.',
    'settings.language.warning': 'Dil uygulandı, ancak cihaz tercihi kaydedilemedi.',
    'settings.language.remoteWarning': 'Sunucu çevirileri alınamadı. Yerel çeviriler kullanılıyor.',
    'welcome.tagline': 'PREMİUM ULAŞIM',
    'welcome.settings': 'Görünüm ve dil ayarlarını aç',
    'welcome.eyebrow': 'AYRICALIKLI ULAŞIM DENEYİMİ',
    'welcome.title': 'Yolculuğunuz,',
    'welcome.highlight': 'konforla başlasın.',
    'welcome.description': 'Havalimanı, otel ve şehir içi transferlerinizi güvenli, konforlu ve zamanında planlayın.',
    'welcome.why': 'NEDEN VIP TRANSFER?',
    'welcome.feature.driver.title': 'Profesyonel Sürücü',
    'welcome.feature.driver.description': 'Deneyimli ve doğrulanmış ekip',
    'welcome.feature.time.title': 'Zamanında Karşılama',
    'welcome.feature.time.description': 'Uçuş ve saat takibi',
    'welcome.feature.safe.title': 'Güvenli Yolculuk',
    'welcome.feature.safe.description': 'Konforlu, bakımlı araçlar',
    'welcome.plan': 'Transfer Planla',
    'welcome.login': 'Giriş Yap',
    'welcome.lookup': 'Rezervasyonumu Görüntüle',
    'welcome.trust': '7/24 transfer hizmeti · Profesyonel sürücüler · Rezervasyon güvencesi',
    'login.title': 'Tekrar Hoş Geldiniz',
    'login.description': 'Rezervasyonlarınıza ve sadakat avantajlarınıza erişmek için giriş yapın.',
    'login.phone': 'Telefon numarası',
    'login.password': 'Şifre',
    'login.passwordPlaceholder': 'Şifrenizi girin',
    'login.show': 'Göster',
    'login.hide': 'Gizle',
    'login.forgot': 'Şifremi Unuttum',
    'login.submit': 'Giriş Yap',
    'login.submitting': 'Giriş Yapılıyor...',
    'login.noAccount': 'Hesabın yok mu?',
    'login.register': 'Kayıt Ol',
    'login.or': 'veya',
    'login.guest': 'Misafir Olarak Devam Et',
    'login.info': 'Bilgi',
    'login.comingSoon': 'Bu özellik henüz hazırlanıyor.',
    'login.error.phoneRequired': 'Telefon numarası gerekli.',
    'login.error.phoneDigits': 'Telefon numarası yalnızca rakamlardan oluşmalı.',
    'login.error.phoneLength': 'Telefon numarası 11 haneli olmalı.',
    'login.error.phoneStart': 'Telefon numarası 0 ile başlamalı.',
    'login.error.passwordRequired': 'Şifre gerekli.',
    'login.error.passwordLength': 'Şifre en az 6 karakter olmalı.',
    'login.error.general': 'Giriş işlemi tamamlanamadı. Lütfen bilgilerinizi kontrol edin.',
    'lookup.eyebrow': 'REZERVASYON SORGULAMA',
    'lookup.title': 'Yolculuk bilgilerinize ulaşın.',
    'lookup.description': 'Rezervasyon kodunuzu ve rezervasyonda kullandığınız telefon numarasını girin.',
    'lookup.code': 'Rezervasyon kodu',
    'lookup.phone': 'Telefon numarası',
    'lookup.submit': 'Rezervasyonu Getir',
    'lookup.loading': 'Rezervasyon Getiriliyor...',
    'lookup.error.codeRequired': 'Rezervasyon kodu gerekli.',
    'lookup.error.phoneRequired': 'Telefon numarası gerekli.',
    'lookup.error.phoneInvalid': 'Geçerli bir 11 haneli telefon numarası girin.',
    'lookup.error.notFound': 'Rezervasyon bulunamadı. Kod ve telefon numarasını kontrol edin.',
    'lookup.error.general': 'Rezervasyon bilgileri alınamadı. Lütfen tekrar deneyin.',
    'transfer.eyebrow': 'VIP TRANSFER REZERVASYONU',
    'transfer.title': 'Transferinizi Planlayın',
    'transfer.description': 'Rotanızı ve yolculuk zamanınızı seçin, size uygun araçları karşılaştırın.',
    'transfer.plan': 'YOLCULUK PLANI',
    'transfer.route': 'Rota',
    'transfer.swap': 'Değiştir',
    'transfer.swapA11y': 'Başlangıç ve varış konumlarını değiştir',
    'transfer.from': 'Nereden',
    'transfer.to': 'Nereye',
    'transfer.pickupPlaceholder': 'Başlangıç noktası seçin',
    'transfer.dropoffPlaceholder': 'Varış noktası seçin',
    'transfer.date': 'Tarih',
    'transfer.time': 'Saat',
    'transfer.selectDate': 'Transfer tarihini seç',
    'transfer.selectTime': 'Transfer saatini seç',
    'transfer.done': 'Tamam',
    'transfer.passenger': 'Yolcu',
    'transfer.passengerCount': '{{count}} kişi',
    'transfer.decreasePassenger': 'Yolcu sayısını azalt',
    'transfer.increasePassenger': 'Yolcu sayısını artır',
    'transfer.continue': 'Uygun Araçları Gör',
    'transfer.resolvingAddress': 'Adres belirleniyor...',
    'transfer.locationError': 'Seçilen konumun adresi bulunamadı.',
    'transfer.futureTime': 'Gelecekte bir saat seçin.',
    'transfer.pastTime': 'Geçmiş bir saat seçilemez.',
    'home.eyebrow': 'VIP TRANSFER HESABIM', 'home.hello': 'Merhaba, {{name}}', 'home.subtitle': 'Yolculuklarını tek yerden planla ve takip et.',
    'home.loyalty': 'Sadakat puanı', 'home.points': '{{count}} puan', 'home.level': '{{level}} seviye', 'home.quick': 'Hızlı işlemler',
    'home.new': 'Yeni rezervasyon', 'home.newHint': 'Rotanı belirle, aracını seç', 'home.reservations': 'Rezervasyonlarım', 'home.reservationsHint': 'Geçmiş ve aktif yolculuklar',
    'home.notifications': 'Bildirim Tercihleri', 'home.notificationsHint': 'E-posta, SMS, anlık bildirim ve WhatsApp',
    'vehicle.eyebrow': 'VIP TRANSFER FİLOSU', 'vehicle.title': 'Size uygun', 'vehicle.highlight': 'aracı seçin.', 'vehicle.description': 'Konfor, kapasite ve başlangıç fiyatlarını karşılaştırarak transfer aracınızı belirleyin.',
    'vehicle.available': 'MÜSAİT ARAÇLAR', 'vehicle.fleet': 'Filomuz', 'vehicle.count': '{{count}} ARAÇ', 'vehicle.hint': 'Devam etmek için bir araç seçin', 'vehicle.continue': 'Devam Et',
    'details.eyebrow': 'REZERVASYON DETAYLARI', 'details.title': 'Yolculuğunuzun özeti', 'details.code': 'REZERVASYON KODUNUZ',
    'details.status': 'Durum', 'details.pickup': 'Başlangıç', 'details.dropoff': 'Varış', 'details.datetime': 'Tarih ve Saat', 'details.passengers': 'Yolcu Sayısı', 'details.vehicle': 'Araç', 'details.distance': 'Mesafe', 'details.total': 'Toplam Tutar', 'details.currency': 'Para Birimi',
    'notifications.title': 'Bildirim Tercihleri', 'notifications.description': 'Size hangi kanallardan ulaşabileceğimizi seçin.', 'notifications.loading': 'Bildirim tercihleri yükleniyor...', 'notifications.failed': 'Tercihler yüklenemedi', 'notifications.always': 'Her zaman açık',
    'notifications.email': 'E-posta', 'notifications.emailDesc': 'Rezervasyon ve hesap bildirimleri e-posta ile gönderilir.', 'notifications.smsDesc': 'Önemli rezervasyon güncellemeleri SMS ile gönderilir.', 'notifications.push': 'Anlık bildirim', 'notifications.pushDesc': 'Uygulama bildirimlerini açın veya kapatın.', 'notifications.whatsappDesc': 'Uygun bildirimleri WhatsApp üzerinden alın.',
  },
  en: {
    'common.selected': 'selected',
    'common.retry': 'Try again',
    'nav.login': 'Sign In',
    'nav.transferSearch': 'Plan a Transfer',
    'nav.appearance': 'Appearance Settings',
    'nav.language': 'Language',
    'nav.notifications': 'Notification Preferences',
    'nav.emailVerification': 'Email Verification',
    'nav.vehicleSelection': 'Vehicle Selection',
    'nav.guestInfo': 'Guest Information',
    'nav.reservation': 'Reservation and Payment',
    'nav.reservations': 'My Reservations',
    'nav.reservationLookup': 'View My Reservation',
    'nav.reservationDetails': 'Reservation Details',
    'settings.theme.title': 'Theme',
    'settings.theme.description': 'Choose the appearance you prefer for the app.',
    'settings.theme.light': 'Light Theme',
    'settings.theme.dark': 'Dark Theme',
    'settings.theme.saved': 'Your theme preference is stored on this device.',
    'settings.theme.warning': 'The theme was applied, but could not be saved on this device.',
    'settings.language.open': 'App Language',
    'settings.language.current': 'Current language: {{language}}',
    'settings.language.title': 'Language',
    'settings.language.description': 'Choose the language you want to use in the app.',
    'settings.language.saved': 'Your language preference is stored on this device.',
    'settings.language.warning': 'The language was applied, but could not be saved on this device.',
    'settings.language.remoteWarning': 'Server translations could not be loaded. Built-in translations are being used.',
    'welcome.tagline': 'PREMIUM TRANSPORTATION',
    'welcome.settings': 'Open appearance and language settings',
    'welcome.eyebrow': 'A PRIVILEGED TRAVEL EXPERIENCE',
    'welcome.title': 'Your journey,',
    'welcome.highlight': 'starts in comfort.',
    'welcome.description': 'Plan your airport, hotel and city transfers safely, comfortably and on time.',
    'welcome.why': 'WHY VIP TRANSFER?',
    'welcome.feature.driver.title': 'Professional Driver',
    'welcome.feature.driver.description': 'Experienced and verified team',
    'welcome.feature.time.title': 'On-time Pickup',
    'welcome.feature.time.description': 'Flight and schedule tracking',
    'welcome.feature.safe.title': 'Safe Journey',
    'welcome.feature.safe.description': 'Comfortable, well-maintained vehicles',
    'welcome.plan': 'Plan a Transfer',
    'welcome.login': 'Sign In',
    'welcome.lookup': 'View My Reservation',
    'welcome.trust': '24/7 transfer service · Professional drivers · Reservation assurance',
    'login.title': 'Welcome Back',
    'login.description': 'Sign in to access your reservations and loyalty benefits.',
    'login.phone': 'Phone number',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.show': 'Show',
    'login.hide': 'Hide',
    'login.forgot': 'Forgot Password',
    'login.submit': 'Sign In',
    'login.submitting': 'Signing In...',
    'login.noAccount': "Don't have an account?",
    'login.register': 'Register',
    'login.or': 'or',
    'login.guest': 'Continue as Guest',
    'login.info': 'Information',
    'login.comingSoon': 'This feature is coming soon.',
    'login.error.phoneRequired': 'Phone number is required.',
    'login.error.phoneDigits': 'Phone number must contain digits only.',
    'login.error.phoneLength': 'Phone number must be 11 digits.',
    'login.error.phoneStart': 'Phone number must start with 0.',
    'login.error.passwordRequired': 'Password is required.',
    'login.error.passwordLength': 'Password must be at least 6 characters.',
    'login.error.general': 'Sign-in could not be completed. Please check your details.',
    'lookup.eyebrow': 'RESERVATION LOOKUP',
    'lookup.title': 'Access your journey details.',
    'lookup.description': 'Enter your reservation code and the phone number used for the reservation.',
    'lookup.code': 'Reservation code',
    'lookup.phone': 'Phone number',
    'lookup.submit': 'Find Reservation',
    'lookup.loading': 'Finding Reservation...',
    'lookup.error.codeRequired': 'Reservation code is required.',
    'lookup.error.phoneRequired': 'Phone number is required.',
    'lookup.error.phoneInvalid': 'Enter a valid 11-digit phone number.',
    'lookup.error.notFound': 'Reservation not found. Check the code and phone number.',
    'lookup.error.general': 'Reservation details could not be loaded. Please try again.',
    'transfer.eyebrow': 'VIP TRANSFER RESERVATION',
    'transfer.title': 'Plan Your Transfer',
    'transfer.description': 'Choose your route and travel time, then compare suitable vehicles.',
    'transfer.plan': 'JOURNEY PLAN',
    'transfer.route': 'Route',
    'transfer.swap': 'Swap',
    'transfer.swapA11y': 'Swap pickup and destination locations',
    'transfer.from': 'From',
    'transfer.to': 'To',
    'transfer.pickupPlaceholder': 'Select pickup point',
    'transfer.dropoffPlaceholder': 'Select destination',
    'transfer.date': 'Date',
    'transfer.time': 'Time',
    'transfer.selectDate': 'Select transfer date',
    'transfer.selectTime': 'Select transfer time',
    'transfer.done': 'Done',
    'transfer.passenger': 'Passengers',
    'transfer.passengerCount': '{{count}} passenger(s)',
    'transfer.decreasePassenger': 'Decrease passenger count',
    'transfer.increasePassenger': 'Increase passenger count',
    'transfer.continue': 'View Available Vehicles',
    'transfer.resolvingAddress': 'Finding address...',
    'transfer.locationError': 'The address for the selected location could not be found.',
    'transfer.futureTime': 'Select a future time.',
    'transfer.pastTime': 'A past time cannot be selected.',
    'home.eyebrow': 'MY VIP TRANSFER ACCOUNT', 'home.hello': 'Hello, {{name}}', 'home.subtitle': 'Plan and track your journeys in one place.',
    'home.loyalty': 'Loyalty points', 'home.points': '{{count}} points', 'home.level': '{{level}} level', 'home.quick': 'Quick actions',
    'home.new': 'New reservation', 'home.newHint': 'Choose your route and vehicle', 'home.reservations': 'My Reservations', 'home.reservationsHint': 'Past and active journeys',
    'home.notifications': 'Notification Preferences', 'home.notificationsHint': 'Email, SMS, push notifications and WhatsApp',
    'vehicle.eyebrow': 'VIP TRANSFER FLEET', 'vehicle.title': 'Choose the', 'vehicle.highlight': 'right vehicle.', 'vehicle.description': 'Compare comfort, capacity and starting prices to choose your transfer vehicle.',
    'vehicle.available': 'AVAILABLE VEHICLES', 'vehicle.fleet': 'Our Fleet', 'vehicle.count': '{{count}} VEHICLES', 'vehicle.hint': 'Select a vehicle to continue', 'vehicle.continue': 'Continue',
    'details.eyebrow': 'RESERVATION DETAILS', 'details.title': 'Your journey summary', 'details.code': 'YOUR RESERVATION CODE',
    'details.status': 'Status', 'details.pickup': 'Pickup', 'details.dropoff': 'Destination', 'details.datetime': 'Date and Time', 'details.passengers': 'Passengers', 'details.vehicle': 'Vehicle', 'details.distance': 'Distance', 'details.total': 'Total Amount', 'details.currency': 'Currency',
    'notifications.title': 'Notification Preferences', 'notifications.description': 'Choose which channels we may use to contact you.', 'notifications.loading': 'Loading notification preferences...', 'notifications.failed': 'Preferences could not be loaded', 'notifications.always': 'Always on',
    'notifications.email': 'Email', 'notifications.emailDesc': 'Reservation and account notifications are sent by email.', 'notifications.smsDesc': 'Important reservation updates are sent by SMS.', 'notifications.push': 'Push notification', 'notifications.pushDesc': 'Turn app notifications on or off.', 'notifications.whatsappDesc': 'Receive eligible notifications through WhatsApp.',
  },
};
